name: Figma Export PDFs
description: Figma Export PDFs

inputs:
  accessToken:
    description: Figma Access Token
    required: true
  fileKey:
    description: Figma File Key
    required: true
  pageNames:
    description: List of pages to export. Default to `all`
    required: true

outputs:
  outDir:
    description: Output directory for all emitted pdf files

runs:
  using: docker
  image: Dockerfile

branding:
  icon: key
  color: gray-dark
