name: Figma Export PDFs
description: Figma Export PDFs

inputs:
  accessToken:
    description: Figma Access Token
    required: true
  fileKey:
    description: Figma File Key
    required: true
  ids:
    description: List of ids to export. Default to `all`
    required: true

outputs:
  pdfs:
    description: List of exported pdfs
  outDir:
    description: Output directory for all emitted pdf files

runs:
  using: docker
  image: Dockerfile

branding:
  icon: file-text
  color: red
