name: Figma Export Diagrams
description: Figma Export Diagrams

inputs:
  accessToken:
    description: Figma Access Token
    required: true
  fileKey:
    description: Figma File Key
    required: true
  ids:
    description: List of ids to export. Default to `all`
    required: true
  exportType:
    description: Type of the export PNG or PDF
    required: true

outputs:
  pdfs:
    description: List of exported diagrams
  outDir:
    description: Output directory for all emitted diagram files

runs:
  using: docker
  image: Dockerfile

branding:
  icon: file-text
  color: red
