name: From Figma

on:
  workflow_dispatch:
    inputs:
      fileKey:
        description: Figma file key
        type: string
        required: true
      page:
        description: Stringified selected page (id, name)
        type: string
        default: '{}'
        required: true
      selection:
        description: Stringified array of the selected nodes (id, name)
        type: string
        default: '[]'
        required: true

jobs:
  export:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Transform Inputs 🧬
        id: transformInputs
        uses: ./.github/actions/transform-inputs
        with:
          fileKey: ${{ github.event.inputs.fileKey }}
          page: ${{ github.event.inputs.page }}
          selection: ${{ github.event.inputs.selection }}

      - name: Figma Export Diagrams 🦾
        id: figmaExportDiagrams
        uses: TwistoPayments/figma-export-diagrams-action@develop
        with:
          accessToken: ${{ secrets.FIGMA_ACCESS_TOKEN }}
          fileKey: ${{ steps.transformInputs.outputs.fileKey }}
          ids: ${{ steps.transformInputs.outputs.ids }}

      - name: Log ℹ️
        run: |
          echo "Results"
          echo "diagrams: $diagrams"
          echo "outDir: $outDir"
        env:
          pdfs: ${{ steps.figmaExportDiagrams.outputs.pdfs }}
          outDir: ${{ steps.figmaExportDiagrams.outputs.outDir }}

      - name: Upload 📂
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ${{ steps.figmaExportDiagrams.outputs.outDir }}
          server-dir: ./pdf-test/
