name: Export diagrams from Figma

on:
  workflow_dispatch:

jobs:
  export-locally:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Figma Export Diagrams 🦾
        id: figmaExportDiagrams
        uses: TwistoPayments/figma-export-diagrams-action@develop
        with:
          accessToken: ${{ secrets.FIGMA_TOKEN }}
          # fileKey: 'VQxKo2pnaksjE7Vql999Qv' #test
          exportType: 'png'
          fileKey: 'ga9i42RTG3E2OxHNj2uJox'   # twisto

      - name: Log ℹ️
        run: |
          echo "Results"
          echo "pdfs: $pdfs"
          echo "outDir: $outDir"
        env:
          pdfs: ${{ steps.figmaExportDiagrams.outputs.pdfs }}
          outDir: ${{ steps.figmaExportDiagrams.outputs.outDir }}

      - name: Upload artifact 📂
        uses: actions/upload-artifact@v3
        with:
          name: my-pdfs
          path: ${{ steps.figmaExportDiagrams.outputs.outDir }}